tipos/enums
Carolis/typescript4noobs pull request #1
Opened 2020-09-21 01:12 UTC by Mdsp9070

- enums
- adicionado paragrafo sobre retorno de função
- adicionado types e interfaces
- splitted types and interfaces

2020-09-21 01:34 UTC, Carolis requested changes
Encontrei alguns errinhos ortográficos e deixei também algumas sugestões!! Qualquer coisa só me dar um toque. 

Agradeço pela contribuição.

2020-09-21 01:34 UTC, Carolis commented on README.md
> +Caso o tipo retornado não correnponda com o tipo do retorno:
Gostei bastante das suas adições! Se não for pedir muito pode corrigir esses erros ortográficos que eu marquei? hehe

2020-09-21 01:34 UTC, Carolis commented on README.md
> +  // não eetorna nenhum valor
Mesmo cenário aqui.
"Arqivo" e "eetorna"

2020-09-21 01:34 UTC, Carolis commented on README.md
> +Seguindo a order, `Baixo == 2`, `Esquerda == 3`, etc...Nesse caso poderíamos declarar apenas as constantes, pois os valores inicais começam do 0.
Talvez seja interessante manter isso aqui em português mesmo, não?

2020-09-21 01:34 UTC, Carolis commented on README.md
> +Tambem é possível defirnir constantes, vulgo, Enums, com strings. Diferente dos numéricos, não há uma ordem de incremeto, logo, é necessário inicializar com um valor real, como:
"Defirnir", se puder corrigir por gentileza também

2020-09-21 01:34 UTC, Carolis commented on README.md
> +```
Não sei se foi um erro de tradução ou algo do gênero mas achei que essa seção não ficou tão legal, só lembrando que heterogeneous enums não são muito recomendados (não sei se foi isso que você quis dizer?)

2020-09-21 01:34 UTC, Carolis commented on README.md
> +  G = "123".length
Se possível manter os exemplos em português para esse repositório =)

2020-09-21 02:02 UTC, Mdsp9070 commented
Desculpa, realmente acabei escrevendo meio que no automático e não prestei atenção na revisão, vou tomar esse cuidado!

2020-09-21 22:46 UTC, Carolis requested changes

2020-09-21 22:46 UTC, Carolis commented on README.md
> +Caso o tipo retornado não correnponda com o tipo do retorno:
"Correnponda"

2020-09-21 22:46 UTC, Carolis commented on README.md
> +entretanto, essa prática não é tão recomendada, inclsive pelo prórpio time do TypeScrit, pois não há muito significado em misturar os tipos de constantes.
Achei a frase "Enums podem possuir mais de um tipo, possuindo diferentes tipos" um pouco confusa, além disso, volto a reiterar que a prática de Enums heterogêneos não é algo legal de se usar e talvez nem seja tão legal colocarmos isso nesse repositório onde a discussão é voltada para um espectro mais "iniciante", já que as situações onde se usa isso são super específicas. Concorda comigo? Talvez seja interessante remover esse tópico.

2020-09-22 00:39 UTC, Mdsp9070 commented on README.md
> +entretanto, essa prática não é tão recomendada, inclsive pelo prórpio time do TypeScrit, pois não há muito significado em misturar os tipos de constantes.
Concordo, vou remover!

2020-09-22 01:22 UTC, merged

2020-09-22 01:23 UTC, Carolis commented
@Mdsp9070 mergeado!! Obrigada pela contribuição =)