Adicionando conteúdo extra
Carolis/typescript4noobs pull request #31
Opened 2024-05-23 12:10 UTC by mateusvieites

Itens adicionados em ordem:
* tipos de lookup / index access types
* extends
* Intersection Types (Union)
* index signature 
* record

2024-05-23 12:18 UTC, Carolis requested changes

2024-05-23 12:18 UTC, Carolis commented on Content/3-Conteudo-Principal/Type-e-Interfaces.md
> +Alguns momentos você pode saber que será recebido itens com um valor com sua tipagem conhecida, porém sem ter o conhecimento da sua chave para existe existem duas formas
```suggestion
Alguns momentos você pode saber que será recebido itens com um valor com sua tipagem conhecida, porém sem ter o conhecimento da sua chave existem duas formas
```

2024-05-23 12:18 UTC, Carolis commented on Content/3-Conteudo-Principal/Type-e-Interfaces.md
> +que são elas "tipos de indexação" e comumente utilizado e recomendado em vários tópicos/livros as recordações(records).
A tradução mais adequada para records aqui acredito que seria **registros** e não recordações

2024-05-23 12:18 UTC, Carolis commented on Content/3-Conteudo-Principal/Type-e-Interfaces.md
> +Exemplo de Recordações:
```suggestion
Exemplo de Registros:
```

2024-05-23 12:20 UTC, mateusvieites commented on Content/3-Conteudo-Principal/Type-e-Interfaces.md
> +Alguns momentos você pode saber que será recebido itens com um valor com sua tipagem conhecida, porém sem ter o conhecimento da sua chave para existe existem duas formas
Erro meu

2024-05-23 12:22 UTC, mateusvieites commented on Content/3-Conteudo-Principal/Type-e-Interfaces.md
> +que são elas "tipos de indexação" e comumente utilizado e recomendado em vários tópicos/livros as recordações(records).
Ambos os casos são utilizados na comunidade ts. Mas será commitado. :D

2024-05-27 13:31 UTC, Carolis approved these changes
Obrigada pela contribuição!

2024-05-27 13:32 UTC, merged